acdh-oeaw/apis-instance-oebl-pfp

pyproject.toml
override-select2js is a dependecy of apis-core since v0.6.3
=> chore(deps): bump apis-core to v0.7.1, drop override-select2js

pyproject.toml
Django is already a dependency of apis-core, therefore we don't have to
list it separately
=> chore(deps): drop django dependency

pyproject.toml
django-allow-cidr is already a dependency of default-settings, and we
are not using it ourselves
=> chore(deps): drop django-allow-cidr

apis_ontology/urls.py
LOGIN_REDIRECT_URL defaults to /accounts/login se we should make that
route available
=> fix: readd django.contrib.auth.urls

apis_ontology/urls.py
apparently the endpoint configured for `apis/admin` does not work
=> fix: readd admin

apis_ontology/forms.py
the GenericModelForm creates the whole form, but the legacy template
also makes a form - so we override the FormHelper for now, until the
template is fixed
=> fix: override FormHelper from GenericModelForm

apis_ontology/importers.py, apis_ontology/querysets.py, apis_ontology/rdfimport/PlaceFromWikidata.toml
This refactors the typesense autocomplete stuff out and then adds a
`apis_ontology.querysets.PlaceExternalAutocomplete`, which inherits from
the typesense class.
It also adds a PlaceImporter and a RDF config file for places from
wikidata.
=> feat: implement place autocomplete and import

apis_ontology/models.py, apis_ontology/settings.py, pyproject.toml
This version of apis-core replaces reversion with apis_core.history, so
we remove all the reversion stuff from our module and add the
apis_core.history app to the INSTALLED_APPS
=> chore(deps): bump apis-core to v0.17.0

apis_ontology/management/commands/import.py
this is because we modify some attributes before reimport, so they
differ and then its a new Source object
=> fix(import): identify source by id

apis_ontology/templates/base.html
We only used that override for adding a `logging` menu item, which we
currently disabled for the time of the import.
=> fix(template): drop login block override

apis_ontology/importers.py, pyproject.toml
The `GenericImporter` from apis-core was renamed to
`GenericModelImporter` and is thus picked automatically for all the
models inheriting from `GenericModel`. This means we don't have to
override it, if we don't want to change its functionality. It now also
automatically tries to import using RDF, therefore we can drop our
overrides for Place and Institution. For Person we still override the
importer, to be able to mangle that data before import, but at least the
inheriting `PersonImporter` now gets a bit smaller.
=> chore(deps): bump apis-core to v0.23.0

apis_ontology/models.py, apis_ontology/settings.py, apis_ontology/templates/auditlog/logentry_list.html, apis_ontology/urls.py, apis_ontology/views.py, pyproject.toml
This adds the django auditlog module and enables it for our ontology
models. It also adds the middleware, so that we have access to the
actor.
We also create an endpoint `/auditlog` that lists the changes made by
the user requesting it.
=> feat(deps): add django-auditlog

apis_ontology/models.py
Profession has multiple CharFields, including one that stores the name
of the Profession entry in the old APIS instance, based on which the
Profession instance was created. When looking up something in
autocomplete, by default all CharFields of a model are searched. This
leads to false positives when searching. Therefore we use the new and
shiny `_default_search_fields` to force the Profession model only to
search the `name` field.
Closes: #293
=> fix(autocomplete): set the _default_search_fields for Profession

apis_ontology/templates/apis_core/apis_entities/abstractentity.html, pyproject.toml
The default settings updates the app order, which is needed to override
the base.html template.
=> chore(deps): bump apis-core-rdf to v0.26.0 & default settings to v1.1.1

apis_ontology/templates/apis_core/apis_entities/abstractentity_form.html, apis_ontology/templates/apis_ontology/place_autocomplete_result.html, apis_ontology/templates/apis_ontology/place_external_autocomplete_result.html
ApisCore now finally (!) ships its own map overlay code, which we can
reuse. Therefore we drop the custom code in the abstractentity_form.html
template and adapt the place_external_autocomplete_result.html template
accordingly.
We also drop the place_autocomplete_result.html template alltogether,
because Apis now also comes with an e53_place_autocomplete_result
template.
=> refactor(templates): use shipped map code

apis_ontology/settings.py
The APIS_LIST_LINKS_TO_EDIT setting is not used anymore in apis-core
The LOGGING setting is now part of the default settings app
The APIS_BASE_URI is set automatically by the default settings app
The LOG_LIST_NOSTAFF_EXCLUDE_APP_LABELS setting was for the
django-action-logger, which is not used anymore.
=> chore: cleanup settings file

apis_ontology/querysets.py
resolves #372
when a url is pasted to the autocomplete
just return an empty queryset to allow for
creation of the object.
=> fix: return empty result for URLs

apis_ontology/importers.py, apis_ontology/rdfimport/EventFromDNB.toml, apis_ontology/rdfimport/PersonFromDNB.toml
resolves #376
Also refactors importer to allow for related entities in a generic way;
adapts events config to that logic
=> fix: add place of birth for GND

apis_ontology/urls.py
Most of them are either defined in apis-core or in default settings
=> feat(urls): drop custom url definitions

apis_ontology/serializers.py
base uri falls back to base domain for RDF serializer if
APIS_BASE_DOMAIN is not set
=> fix: do not rely on APIS_BASE_URI

apis_ontology/importers.py, apis_ontology/rdfimport/InstitutionFromDNB.toml, apis_ontology/rdfimport/PersonFromDNB.toml, apis_ontology/rdfimport/PlaceFromDNB.toml
=> fix: add logic for sameAs

apis_ontology/models.py
The migrations for this field were apparently made with `null=True` but
this is not reflected in the models.py, so we add this argument now.
=> fix(models): let the alternative_names field be null

apis_ontology/serializers.py
resolves #450
Additionally moves reference resource id descriptions, so that
these definitions are only added when uris really exist.
=> fix: add APIS IDs to all entities
