- apis_ontology/settings.py
> fix: use default-settings

- apis_ontology/models.py
- apis_ontology/templates/apis_entities/edit_generic.html
> fix: show source info in edit header

- apis_ontology/settings.py
> fix: use apis-acdhch-default-settings middleware list

- apis_ontology/management/commands/tag_matching.py
- apis_ontology/management/commands/xml_collection_ok.py
add script to put all the contenttype_id/object_id of instances where db
and xml are matching in one file
add script to load all the matching id's and tag them using a collection
> feat: scripts to store and load matching occurrences

- apis_ontology/filtersets.py
- apis_ontology/templates/apis_entities/edit_generic.html
- apis_ontology/urls.py
- feat: switch to generic List view
- feat: override default entity filterset for person
- feat: show collection workflow in edit template
> Switch listview and include collections

- apis_ontology/models.py
> fix: show firstname/lastname for person as default string

- pyproject.toml
> chore(deps): bump highlighter to first uploaded release v0.1.3

- apis_ontology/settings.py
we are not using APIS_ENTITIES anymore
> fix: remove unused settings

- apis_ontology/forms.py
> fix(form): move some texts outside of form, other attributes to details

- apis_ontology/importers.py
- apis_ontology/querysets.py
- apis_ontology/rdfimport/PersonFromWikidata.toml
Update importer for new rdf method
Add rdf parser definition to `rdfimports`
Add PersonExternalAutocomplete to querysets
> feat: import people from wikidata

- apis_ontology/management/commands/relations.py
> fix: Add InstitutionInstitution relation

- apis_ontology/querysets.py
- apis_ontology/rdfimport/InstitutionFromDNB.toml
- apis_ontology/rdfimport/InstitutionFromWikidata.toml
- apis_ontology/rdfimport/PersonFromDNB.toml
- apis_ontology/rdfimport/PersonFromWikidata.toml
- apis_ontology/rdfimport/PlaceFromDNB.toml
- apis_ontology/rdfimport/PlaceFromGeonames.toml
- apis_ontology/rdfimport/PlaceFromWikidata.toml
> feat: fix person import and add institution import

- apis_ontology/management/commands/relations_import_from_json.py
instead of `self_contenttype` which seems to be buggy
> fix: use contenttype for import script

- apis_ontology/signals.py
> fix: move pointer of texts or append texts to existing ones

- apis_ontology/management/commands/import.py
- apis_ontology/models.py
> fix: drop texttypes

- apis_ontology/settings.py
- apis_ontology/urls.py
> fix(settings): disable logger for now

- apis_ontology/management/commands/import.py
See https://github.com/acdh-oeaw/apis-instance-oebl-pnp/issues/10
> fix(management): skip uri 60485

- apis_ontology/filtersets.py
Use `*_place` filter method for `Place` filter set.
> fix: filter method

- apis_ontology/templates/base.html
> fix(templates): add parentprofession to menu

- apis_ontology/filtersets.py
- apis_ontology/models.py
- pyproject.toml
... and adapt the filtersets, to override the new default `search`.
Also use the new `_default_search_fields` attribute for models.
> chore(deps): bump apis-core-rdf to v0.24.0

- apis_ontology/rdfimport/PersonFromDNB.toml
> fix: change DNB person sparql to make name retrieval more flexible

- pyproject.toml
> chore: bump apis-core-rdf

- apis_ontology/filtersets.py
to allow for search with base characters instead
of diacritics we add posgres unaccent to filters
resolves #353
> fix: add unaccent to the search filters

- apis_ontology/filtersets.py
> fix: normalize special characters from search

- apis_ontology/rdfimport/EventFromDNB.toml
resolves #376
adds support for `gndo:ConferenceOrEvent`
> fix: allow for more event types

- apis_ontology/serializers.py
adds a serializer for Personinstitution Relations;
adds proper birth and death events
> feat: improve cidoc serializers

- apis_ontology/models.py
> fix: add more types of alternative names

- apis_ontology/serializers.py
> fix: add missing slash in entities uris

- apis_ontology/models.py
> fix: add blank class to models with RDF serializer

- apis_ontology/serializers.py
> fix: refactor serializers; add inst serializer

- apis_ontology/serializers.py
> fix: errors in CIDOC serializers

- apis_ontology/models.py
> fix: entity str() should return a string

- apis_ontology/serializers.py
> fix: add missing triples in CIDOC

- apis_ontology/serializers.py
> fix: error regarding RDFLib term

- apis_ontology/serializers.py
> fix: change RDF date serialization

- apis_ontology/rdfimport/PlaceFromGeoNames.toml
- apis_ontology/rdfimport/ProfessionFromDNB.toml
- apis_ontology/rdfimport/ProfessionFromWikidata.toml
> fix: add config for GeoNames

- apis_ontology/filtersets.py
- pyproject.toml
> fix: add django-interval filterfield

- apis_ontology/tables.py
> fix: change rel table name

- apis_ontology/templates/apis_core/apis_entities/abstractentity.html
... and update template for bootstrap 5
> feat(template): use new collections toggle templatetag

- apis_ontology/rdfimport/InstitutionFromDNB.toml
> fix: extend importer to OrganOfCorporateBody

- apis_ontology/filtersets.py
- apis_ontology/querysets.py
> fix: adapt qs and filters to new inst model

- apis_ontology/importers.py
- apis_ontology/models.py
- apis_ontology/rdfimport/PrizeFromDNB.toml
- apis_ontology/rdfimport/PrizeFromWikidata.toml
> fix: add import configs for prize

- apis_ontology/serializers.py
... now that there is a E74_GroupCidocSerializer
> refactor(serializers): drop custom serializer
